apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "-product-infrastructure"
  description: {{ parameters.description }}
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/github-folder: 'HMCTS_/-product-infrastructure'
    github.com/project-slug: ''
  tags:
    - terraform
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=
      title:  on Slack
      icon: chat
spec:
  type: service
  lifecycle: experimental
  owner: {{ parameters.owner }}
